### ISSUE TITLE
sendmessage2Client in ioBroker

### ISSUE THREAD

**Issue by HeXaN-Prime** [sebbo2002/pyatv-mqtt-bridge#181]
Hey,

can any body told me how to send message via blocky to pyatv-mqtt-bridge?

greetings

**Comment by sebbo2002** [comment]
I don't use ioBroker and can't help you there, sorry.

**Comment by HeXaN-Prime** [comment]
Ok i found a solution an it is very easy! maybe I can help somebody:
(In the topic use your own name. My is "appletv")

![image](https://user-images.githubusercontent.com/74064892/185804756-9604b947-fb30-4265-b9ed-0e12446cef87.png)
