### ISSUE TITLE
Docker Container - cyclic mqtt messages

### ISSUE THREAD

**Issue by Schnittcher** [sebbo2002/pyatv-mqtt-bridge#214]
Hello,

can you help? I don't get mqtt messages from the docker container, only after restart the conatiner.
Are there no cyclic MQTT messages?

Edit: Ahh, this is wrong, only the position is not updated. When I paused playback then the status is updated. Can you help?

Thanks in advance,
kai

**Comment by sebbo2002** [comment]
The position only updates when pyatv sends this position, for example when the video is paused or started. MQTT clients can then use this data to extrapolate when a certain position is reached, for example. Does that help you?
