### ISSUE TITLE
How to remote control?

### ISSUE THREAD

**Issue by Youaresmarter** [sebbo2002/pyatv-mqtt-bridge#22]
Hi!
How to remote control? What topics and values?

**Comment by sebbo2002** [comment]
To execute a command send any message to the topic `$device/$commad`. `$device` is the configured topic of the device
and `$command` is a command from [this list](https://github.com/sebbo2002/node-pyatv/blob/develop/lib/types.ts#L49). 

Example: `/home/living/appletv/menu`.

I have also put this in the FAQ for the next person who asks this question.
