### ISSUE TITLE
Launching Apps

### ISSUE THREAD

**Issue by terminaldisclaimer** [sebbo2002/pyatv-mqtt-bridge#223]
Have you considered adding the possibility to launch apps? I think that would be a great feature and would allow integration into a lot of different automation platforms.

**Comment by sebbo2002** [comment]
I have seen that pyatv has a [python API](https://pyatv.dev/development/apps/) to run apps. Via [`atvremote`](https://pyatv.dev/documentation/atvremote/#apps), this feature could also be built into pyatv-mqtt-bridge. If there is a critical mass here that would like to see this feature, I would implement it, but haven't done so myself yet as I don't currently need this feature. Of course pull requests are always welcome.

**Comment by pluto202** [comment]
I would be interested as well on that option.

**Comment by sebbo2002** [comment]
1/2 https://github.com/sebbo2002/node-pyatv/commit/680d1deb83882a87b246e621cbce6237c9741825

**Comment by sebbo2002** [comment]
Do you want to test it?
- 📦 **npm:** `npm install @sebbo2002/pyatv-mqtt-bridge@next`
- 🐳 **Docker:** `docker pull sebbo2002/pyatv-mqtt-bridge:next`
