### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by chrigu1981** [sebbo2002/pyatv-mqtt-bridge#23]
Hello

i did not tested your library so far but could we extend it to do the paring over MQTT?
Also it would be nice to have a Dockerfile 😉

**Comment by sebbo2002** [comment]
This library is based on node-pyatv which uses [atvscript](https://pyatv.dev/documentation/atvscript/) to connect to the device. As far as I know, the script currently has no way of pairing. You would have to use [atvremote](https://pyatv.dev/documentation/atvremote/#pairing-with-a-device) and parse the output, which would probably break quickly. Therefore, this feature is currently not implemented.

If it's okay with you, I would rename the issue to address the second point, the missing Dockerfile.

**Comment by chrigu1981** [comment]
thx for clarification about pairing...
sure just rename as you want

**Comment by sebbo2002** [comment]
There's now a ready to be used [docker image](https://hub.docker.com/r/sebbo2002/pyatv-mqtt-bridge) based on alpine. I also updated the readme file.

**Comment by chrigu1981** [comment]
very nice 😍 thank you @sebbo2002
