### ISSUE TITLE
Docker Image Update

### ISSUE THREAD

**Issue by thk-socal** [sebbo2002/pyatv-mqtt-bridge#280]
Would love to see the Docker image updated to the latest release of pyatv. Current Docker image is at 0.9.7 and latest I see is 0.14.4.

**Comment by sebbo2002** [comment]
Hmm, actually the Docker base image should be updated automatically by Dependabot. I'll do a manual update later today and see if I can figure out why Dependabot is no longer generating updates. Thanks for bringing this to my attention.
