### ISSUE TITLE
MQTT Values on Volume Change

### ISSUE THREAD

**Issue by thk-socal** [sebbo2002/pyatv-mqtt-bridge#285]
Love the MQTT data, but I have an issue when the volume changes from another device.

Example: Music starts playing and you get title, time, status etc... into MQTT and have the data to drive other automations.
However, if the volume is adjusted from another device, say an iPhone, the previous data is removed from MQTT and you do not have all the other information from the previous values there. 

Feature Request: Maintain the previous values in MQTT when volume changes happen from another device.

**Comment by thk-socal** [comment]
Perhaps a "retainMQTT" with true/false flag per device in the configuration file that then triggers MQTT retain on messages.

**Comment by sebbo2002** [comment]
To be honest, I haven't really figured out the problem yet. The retain flag is set for every publish, so the data should still be available on the broker. Have you started the bridge with `--debug`? Can you post the log here?

https://github.com/sebbo2002/pyatv-mqtt-bridge/blob/develop/src/lib/index.ts#L113

**Comment by thk-socal** [comment]
With 0.9.7 of pyatv it does not happen, but with 0.14.4 it does. The value for "volume" was added to the newer versions and when it is passed, pyatv-mqtt-bridge sets the other values to null as they are not passed from pyatv and I think they are expected.

So yes, the settings are retained, but in this case they are set to null. I am pretty sure it is because the volume is not properly handled in the code.

2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"volume","old":null,"new":53.8,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"repeat","old":"off","new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"shuffle","old":"off","new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"position","old":148,"new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"totalTime","old":286,"new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"genre","old":"Rock","new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"album","old":"Toto","new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"artist","old":"Toto","new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"title","old":"You Are the Flower","new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"deviceState","old":"playing","new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"mediaType","old":"music","new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"hash","old":"ELMg8u54T::o8y7E098D","new":null,"device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}
2023/11/06 17:13:39	stdout	[info][192.168.3.6] {"values":{"key":"dateTime","old":"2023-11-07T01:13:32.901Z","new":"2023-11-07T01:13:39.352Z","device":{"name":"Master Bedroom HomePod","host":"192.168.3.6","id":"94:EA:32:A2:34:9A"}}}

**Comment by sebbo2002** [comment]
Aaah. Sorry, it took me a little longer. So `volume` events do not send all other data, but only `volume`. This is currently not properly handled in `node-pyatv`'s [`parseState()`](https://github.com/sebbo2002/node-pyatv/blob/aa99e8fcee85a0044442b1ef564c933f4d17f0f3/src/lib/tools.ts#L237) or in [`applyStateAbdEmitEvents()](https://github.com/sebbo2002/node-pyatv/blob/aa99e8fcee85a0044442b1ef564c933f4d17f0f3/src/lib/device-events.ts#L38C5-L38C28).

I can take care of it this week or next week when I get around to it. It will probably take me a few days to find the time though. Otherwise, you're welcome to submit a PR if you need to have it now.

**Comment by thk-socal** [comment]
No rush. Just submitting the issues as I find them. Glad you know where it is and can fix it at some point. I created a quick work around in my Node-Red flows to handle for now as I did not have time to research and change the code. Thanks for a great addition to the community!

**Comment by sebbo2002** [comment]
@thk-socal Unfortunately, I cannot reproduce a `volume` event here. I suspect that this is because my Apple TV remote control controls the volume via IR, not the Apple TV via HDMI CEC. I have published version 7.0.0-develop.4 (`npm i @sebbo2002/pyatv-mqtt-bridge@7.0.0-develop.4`), which logs the raw output of pyatv again if started in debugging mode. Can you post the output here again? Thank you very much.

**Comment by thk-socal** [comment]
I can look at this over the weekend. Might be easier to grab the volume event from my Homepod, which is a great use of this tool as well.
