### ISSUE TITLE
Cannot start container

### ISSUE THREAD

**Issue by bernd70** [sebbo2002/pyatv-mqtt-bridge#301]
Hi,

after using the bridge for a while after updating to 7.0.1 I cannot start the container with an error:

_Error response from daemon: unable to find user node: no matching entries in passwd file_

It appears the user "node" is missing in the container?

Version 6.0.3 starts just fine.

I am running docker on an Unraid server.

I tried with docker-compose as well, but gut the same error:

```version: "3"
services:
  pyatv-mqtt-bridge:
    container_name: pyatv-mqtt-bridge
    image: sebbo2002/pyatv-mqtt-bridge
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /mnt/user/appdata/pyatv-mqtt-bridge/config.json:/app/config.json:ro
    command: pyatv-mqtt-bridge /app/config.json
```

Any idea how to fix this?

Regards
Bernd

**Comment by bernd70** [comment]
I guess the reason is a change in the Dockerfile: 

There is a user "app" added

`adduser -u 1000 -G app -s /bin/sh -D app && \`

In 6.3 this user is used with "USER app", in 7.0 there is "USER node", but this user is never created...

**Comment by sebbo2002** [comment]
Sorry, the error apparently happened when merging from my template. Should work with the new version.

**Comment by bernd70** [comment]
Works with the new release,thank you. :-)
