### ISSUE TITLE
Missing armv7 builds

### ISSUE THREAD

**Issue by glecoz** [sebbo2002/pyatv-mqtt-bridge#306]
I was wondering why my Apple TV wasn't turning off properly while leaving home, just because the MQTT /powerState subtopic wasn't published anymore to my broker, so I just updated my docker-compose file with the latest armv7 image available :

``image: sebbo2002/pyatv-mqtt-bridge:80a6b204a0b95acd608b179abb2e2d8f9136fb0e``

Now it's working fine again, but would you mind providing the armv7 images again (if built automatically) ? There are still tons of Raspberry Pi armv7 online out there (mine is Pi 4 B bought brand new 2 years ago), bcs we now get the following error :

```
docker pull sebbo2002/pyatv-mqtt-bridge

Using default tag: latest
latest: Pulling from sebbo2002/pyatv-mqtt-bridge
no matching manifest for linux/arm/v7 in the manifest list entries
```

Otherwise we need to `git pull` your repo regularly, and `docker-compose --build` each time from your Dockerfile. 😓

Thanks.

![image](https://github.com/sebbo2002/pyatv-mqtt-bridge/assets/1590118/f469ffcf-a08b-47b2-bd2e-91da3f6ede89)

**Comment by sebbo2002** [comment]
Docker Images for armv7 were removed with [pyatv-mqtt-bridge@7.0.0](https://github.com/sebbo2002/pyatv-mqtt-bridge/releases/tag/v7.0.0) as pyatv [removed their armv7 images as well](https://github.com/sebbo2002/pyatv-mqtt-bridge/commit/2f79b2fdea88704032eb40eb3672dd588c9f3cc2). You can easily check this by building the current Dockerfile:

```
docker build -t pyatv-mqtt-bridge --platform linux/arm/v7 .                       ✘ 1 
[+] Building 1.2s (3/3) FINISHED                                                            docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                        0.0s
 => => transferring dockerfile: 1.04kB                                                                      0.0s
 => [internal] load .dockerignore                                                                           0.0s
 => => transferring context: 87B                                                                            0.0s
 => ERROR [internal] load metadata for ghcr.io/postlund/pyatv:latest                                        1.1s
------
 > [internal] load metadata for ghcr.io/postlund/pyatv:latest:
------
Dockerfile:14
--------------------
  12 |     
  13 |     
  14 | >>> FROM ghcr.io/postlund/pyatv:latest
  15 |     ARG NODE_ENV=production
  16 |     ENV NODE_ENV=$NODE_ENV
--------------------
ERROR: failed to solve: ghcr.io/postlund/pyatv:latest: no match for platform in manifest sha256:779d835e3bfb83bdbfbf472acc9ea77cce8f166554335006a5beac3cee528132: not found
```

The Docker image of pyatv-mqtt-bridge is based on this Docker image, so I had to stop the v7 support as well. Please open a ticket for [pyatv](https://github.com/postlund/pyatv) to reintroduce armv7 there, afterwards I can do the same here.

**Comment by glecoz** [comment]
Thx @sebbo2002, request [sent](https://github.com/postlund/pyatv/issues/2324) 🤞

**Comment by glecoz** [comment]
Thx for the detailed answer, request sent.
