### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by Schnittcher** [sebbo2002/pyatv-mqtt-bridge#356]
Hi,

wenn ich den Docker Container auf dem Synology laufen lassen, erhalte ich im Debug immer device_not_found.
Wenn ich den atvscript Befehl in der Konsole ohne den Parameter -s aufrufe funktioniert es.

Das Synology ist in einem anderen VLAN als der AppleTV.

Hast du eine Idee?

Grüße,
Kai

**Comment by sebbo2002** [comment]
Was passiert denn, wenn du `host` auf einen leeren String änderst (`"host": ""`)? Habe das jetzt nicht getestet, aber das sollte in `node-pyatv` auch einfach den `-s` Parameter weglassen. Wird dann nur vermutlich etwas langsamer sein. 

Ansonsten würde ich vielleicht mal bei https://github.com/postlund/pyatv nachfragen, die kennen sicher eher mit dem Protokoll aus. Vielleicht haben die eine Idee warum es mit `-s` nicht funktioniert.

**Comment by Schnittcher** [comment]
Danke, das funktioniert.
Ich hatte den Host komplett entfernt, das hatte natürlich nicht funktioniert, auf die Idee mit einem leeren String bin ich nicht gekommen... :-D

Grüße,
Kai
