### ISSUE TITLE
Question: How to get NodePyATVPowerState events?

### ISSUE THREAD

**Issue by bytedealer** [sebbo2002/pyatv-mqtt-bridge#90]
Hi @sebbo2002!

What a great piece of software! I successfully set up pyatv-mqtt-bridge in a docker container. I subscribed to the topics and boom - it works. One thing I am missing the power state events. I found them in pyatv-node but it seems I am doing something wrong because I don't get them.

Could you please give me a hint?

Thanks a lot and in advance!
bytedealer

**Comment by sebbo2002** [comment]
Phuu, no idea how the PowerState behaves. I don't use it for my home automation use case.

I'm currently on vacation and of course don't have an Apple TV with me. I'll be happy to take a look at it afterwards, but it probably will take a few more weeks.

**Comment by bytedealer** [comment]
Hey @sebbo2002!

That would be fantastic! To level up your imagination one example as scenario: You press the button of the appletv remote and it sends an PowerState "on", then you can switch on your "movie lights" (but only if the lumen is low or the day of time is evening).

One button press and a lot of "magic". :-)

Big thanks for looking for a solution.

Enjoy your vacation!
bytedealer

**Comment by bytedealer** [comment]
HI @sebbo2002,

I can close the ticket. I tried to simulate the power off with using the standby function within AppleTV. And using this way there is no reaction on the topic. BUT if you are waiting and the AppleTV goes to sleep itself, then I get a response ("off"). And if I start the AppleTV via remote tehen I get a response ("on"), too.

So, I think there could be a bug in pyatv or AppleTV.

Thanks for your time and the great software!
bytedealer

P.S.: Besides you should update your example, there is the "name" section missing.

**Comment by postlund** [comment]
The standby function is deprecated solely because it doesn't work as expected, use `turn_off` instead. Preferably also with credentials for the Companion protocol set (you get the same functionality as when using a shortcut if you do).
